name: Get

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install ClaudeCode
        shell: pwsh
        run: |
          irm https://claude.ai/install.ps1 | iex

      - name: Windows archive
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v5
        with:
          name: zed_${{ matrix.os }}
          path: |
